### PR TITLE
Turn profiling on/off runtime

### LINKED ISSUE #532: enable/disable profile at runtime
Easegress could generate CPU & memory profiles for troubleshooting, but this feature can only be enabled from the configuration at startup.

However, some issues only happen after Easegress runs for a long time, if profiling is not enabled at first, it will be very hard to reproduce the issue.

So, we need to add new admin APIs to enable/disable profiles at runtime.

### PR DESCRIPTION
**Pull request by samutamm**
...using admin API.

Close #532

### CODE REVIEW

File: pkg/api/profile.go [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+	"sync"
+)
+
+const (
+	// ProfilePrefix is the URL prefix of profile APIs
+	ProfilePrefix = "/profile"
+	// StartAction is the URL for starting profiling
+	StartAction = "/start"
+	// StopAction is the URL for stopping profiling
+	StopAction = "/stop"
```
Comment (localvar) [inline pkg/api/profile.go:33]:
```suggestion
	StartAction = "start"
	// StopAction is the URL for stopping profiling
	StopAction = "stop"
```

File: pkg/api/profile.go [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+			Method:  http.MethodPost,
+			Handler: s.startCPUProfile,
+		},
+		{
+			Path:    fmt.Sprintf("%s%s/memory", ProfilePrefix, StartAction),
+			Method:  http.MethodPost,
+			Handler: s.startMemoryProfile,
+		},
+		{
+			Path:    fmt.Sprintf("%s%s", ProfilePrefix, StopAction),
```
Comment (localvar) [inline pkg/api/profile.go:67]:
```suggestion
			Path:    fmt.Sprintf("%s/%s/cpu", ProfilePrefix, StartAction),
			Method:  http.MethodPost,
			Handler: s.startCPUProfile,
		},
		{
			Path:    fmt.Sprintf("%s/%s/memory", ProfilePrefix, StartAction),
			Method:  http.MethodPost,
			Handler: s.startMemoryProfile,
		},
		{
			Path:    fmt.Sprintf("%s/%s", ProfilePrefix, StopAction),
```

File: pkg/api/profile.go [hunk 3]
```diff
@@ -0,0 +1,114 @@
...
+
+func (s *Server) startCPUProfile(w http.ResponseWriter, r *http.Request) {
+	spr := StartProfilingRequest{}
+	err := yaml.NewDecoder(r.Body).Decode(&spr)
+	if err != nil {
+		HandleAPIError(w, r, http.StatusBadRequest, fmt.Errorf("bad request"))
+		return
+	}
+
+	s.opt.CPUProfileFile = spr.Path
```
Comment (localvar) [inline pkg/api/profile.go:94]: need to check if spr.Path is valid or not.

File: cmd/client/command/profile.go [hunk 4]
```diff
@@ -0,0 +1,114 @@
...
+	cmd.AddCommand(infoProfileCmd())
+	cmd.AddCommand(startProfilingCmd())
+	cmd.AddCommand(stopProfilingCmd())
+	return cmd
+}
+
+func infoProfileCmd() *cobra.Command {
+	cmd := &cobra.Command{
+		Use:   "info",
+		Short: "Show memory and CPU profile file paths.",
```
Comment (xxx7xxxx) [inline cmd/client/command/profile.go:43]:
```suggestion
		Short: "Show memory and CPU profile file paths",
```

Consistent with other commends, no period in short usage. So are others

File: pkg/api/profile.go (hunk 3 above)
Comment (xxx7xxxx) [inline pkg/api/profile.go:94]: I don't think directly changing fields of options is a good idea. The options should truly reflect the static options, which will be put into etcd as member info. So my proposal is to make function be like `profile.StartCPUProfile(path string)` which uses `options.CPUProfilePath` only if path is empty.

**Comment by localvar** [comment]
@samutamm , seems two different changes are in the PR

**Comment by samutamm** [comment]
> @samutamm , seems two different changes are in the PR

Oups! Now it looks ok again

File: pkg/api/profile.go [hunk 5]
```diff
@@ -0,0 +1,138 @@
...
+
+func (s *Server) startCPUProfile(w http.ResponseWriter, r *http.Request) {
+	spr := StartProfilingRequest{}
+	err := yaml.NewDecoder(r.Body).Decode(&spr)
+	if err != nil {
+		HandleAPIError(w, r, http.StatusBadRequest, fmt.Errorf("bad request"))
+		return
+	}
+
+	if spr.Path == "" || !IsPathValid(spr.Path) {
```
Comment (localvar) [inline pkg/api/profile.go:95]: I comment before to validate `spr.Path`, but I think we only need to check if it is an empty string.
because even `IsPathValid` returns true, it does not mean the path is valid when it is actually used.
and for L99, we can update `UpdateCPUProfile` to return an error and forward the error to the client.

**Review by localvar — APPROVED** [review]

**Review by suchen-sci — APPROVED** [review]

File: pkg/profile/profile.go [hunk 6]
```diff
@@ -45,20 +57,38 @@ func New(opt *option.Options) (Profile, error) {
...
+		return ""
+	}
+	return p.cpuFile.Name()
+}
+
+func (p *profile) MemoryFileName() string {
+	return p.memFileName
+}
+
+func (p *profile) UpdateMemoryProfile(fp string) {
```
Comment (xxx7xxxx) [inline pkg/profile/profile.go:79]: There could be concurrent calls from the network, we need to handle it, don't we? So do others.

Comment (samutamm) [reply pkg/profile/profile.go:79]: I think that we can suppose that there is only one administrator, who wants to turn on/off profiling at once.. However do you think that concurrent calls can cause runtime errors? I'll add the lock like in other admin APIs.

Comment (xxx7xxxx) [reply pkg/profile/profile.go:79]: We can't make assumptions from users. Runtime errors would be many kinds of race conditions.

Comment (samutamm) [reply pkg/profile/profile.go:79]: Yeah true.. Now it should be better, with lock for modifications.

File: pkg/api/profile.go [hunk 7]
```diff
@@ -94,6 +94,10 @@ func (s *Server) startCPUProfile(w http.ResponseWriter, r *http.Request) {
 		HandleAPIError(w, r, http.StatusBadRequest, fmt.Errorf("missing path"))
 		return
 	}
+
+	s.Lock()
```
Comment (xxx7xxxx) [inline pkg/api/profile.go:98]: You misused the lock which is the cluster-level config lock. The lock we should use is the localprofile-leveled.

**Review by xxx7xxxx — APPROVED** [review]
