### PR TITLE
remove goroutine from a test (close #347)

### LINKED ISSUE #347: MQTT test case fails randomly
**Describe the bug**
MQTT test case fails randomly

**To Reproduce**

1. switch to directory `pkg/object/mqttproxy`
2. execute `go test` for several times
3. test cases failed randomly

### PR DESCRIPTION
**Pull request by samutamm**
Fix https://github.com/megaease/easegress/issues/347.

There was nondeterministic issue with http.Server creation and closing and sending messages. 
- Changing [topicsPublish](https://github.com/megaease/easegress/blob/main/pkg/object/mqttproxy/mqtt_test.go#L852-L867) invocations from concurrent goroutines to sequential invocations to avoid race condition
- Modify mqtt_test.go's testServer.start() to wait until the server is ready

To verify that test fails 0/30 runs :
```bash
cd pkg/object/mqttproxy 
for (( i=0; i < 30; i=i+1 )); do go test | tail -n 1 | cut -c 1-4; done
```
and output should have only `ok`'s.

## Todo
I found new error that should be investigated
`--- FAIL: TestCleanSession (0.00s)
    mqtt_test.go:231: topicMgr should contain topic test/cleanSession/0 when client reconnect, but got map[]`

### CODE REVIEW

**Review by megaeasex — APPROVED** [review]
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 353 Deploy Test Success

**Review by megaeasex — APPROVED** [review]
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 353 Deploy Test Success

File: pkg/object/mqttproxy/mqtt_test.go [hunk 1]
```diff
@@ -841,8 +845,18 @@ func (ts *testServer) addHandlerFunc(pattern string, f http.HandlerFunc) {
 	ts.mux.HandleFunc(pattern, f)
 }
 
-func (ts *testServer) start() {
+func (ts *testServer) start() error {
 	go ts.srv.ListenAndServe()
+	// Poll server until it is ready
+	for t := 0; t < 5; t++ {
+		time.Sleep(20)
```
Comment (localvar) [inline pkg/object/mqttproxy/mqtt_test.go:852]:
```suggestion
		time.Sleep(20 * time.Millisecond)
```

**Review by megaeasex — APPROVED** [review]
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 353 Deploy Test Success

**Review by megaeasex — APPROVED** [review]
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 353 Deploy Test Success

**Review by localvar — APPROVED** [review]

File: pkg/object/mqttproxy/mqtt_test.go [hunk 2]
```diff
@@ -841,8 +845,18 @@ func (ts *testServer) addHandlerFunc(pattern string, f http.HandlerFunc) {
 	ts.mux.HandleFunc(pattern, f)
 }
 
-func (ts *testServer) start() {
+func (ts *testServer) start() error {
 	go ts.srv.ListenAndServe()
+	// Poll server until it is ready
+	for t := 0; t < 25; t++ {
+		time.Sleep(50 * time.Millisecond)
+		req, _ := http.NewRequest(http.MethodGet, "http://localhost:"+ts.addr, nil)
```
Comment (suchen-sci) [inline pkg/object/mqttproxy/mqtt_test.go:853]: This `ts.addr` here is `:8888`, you combine with "http://localhost:" will become "http://localhost::8888", replace it with simple ts.addr will work
```suggestion
		req, _ := http.NewRequest(http.MethodGet, ts.addr, nil)
```

**Review by megaeasex — APPROVED** [review]
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 353 Deploy Test Success

**Review by suchen-sci — APPROVED** [review]

**Review by megaeasex — APPROVED** [review]
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 353 Deploy Test Success
