### PR TITLE
fix #738 panic in demo

### LINKED ISSUE #738: Panic On demo
Commit 7d9f590 

1. egctl --server  127.0.0.1:12381 object create -f pipeline-demo.yaml
``` 
name: pipeline-demo
kind: Pipeline
flow:
  - filter: proxy
filters:
  - name: proxy
    kind: Proxy
    pools:
    - servers:
      - url: http://127.0.0.1:9095
      - url: http://127.0.0.1:9096
      - url: http://127.0.0.1:9097
      loadBalance:
        policy: roundRobin
```
2. egctl --server  127.0.0.1:12381 object create -f server-demo.yaml
```
kind: HTTPServer
name: server-demo
port: 10080
keepAlive: true
https: false
rules:
  - paths:
    - pathPrefix: /pipeline
      backend: pipeline-demo
```
3. egctl --server  127.0.0.1:12381 object   delete server-demo

primary-001 panic 退出

```log
goroutine 223 [running]:
github.com/megaease/easegress/pkg/object/statussynccontroller.(*statusUnit).clusterKey(...)
	github.com/megaease/easegress/pkg/object/statussynccontroller/statussynccontroller.go:91
github.com/megaease/easegress/pkg/object/statussynccontroller.(*StatusSyncController).syncStatusToCluster(0xc00231a060, 0xc002caaff0)
	github.com/megaease/easegress/pkg/object/statussynccontroller/statussynccontroller.go:240 +0x16a
github.com/megaease/easegress/pkg/object/statussynccontroller.(*StatusSyncController).handleStatus(0xc00231a060, 0x62e7bfd2)
	github.com/megaease/easegress/pkg/object/statussynccontroller/statussynccontroller.go:230 +0x94
github.com/megaease/easegress/pkg/object/statussynccontroller.(*StatusSyncController).run(0xc00231a060)
	github.com/megaease/easegress/pkg/object/statussynccontroller/statussynccontroller.go:173 +0x3d
created by github.com/megaease/easegress/pkg/object/statussynccontroller.(*StatusSyncController).reload
	github.com/megaease/easegress/pkg/object/statussynccontroller/statussynccontroller.go:166 +0x136
```

code
```golang
func (ssc *StatusSyncController) syncStatusToCluster(statusUnits map[string]*statusUnit) {
   // Delete statuses which disappeared in current status.
   if ssc.lastSyncStatusUnits != nil {
     kvs := make(map[string]*string)
     for k := range ssc.lastSyncStatusUnits {
       if su, exists := statusUnits[k]; !exists {                <=== when exists false, su is nil? 
         k = su.clusterKey(ssc.superSpec.Super().Cluster().Layout())
         kvs[k] = nil
       }
     }
     err := ssc.superSpec.Super().Cluster().PutAndDeleteUnderLease(kvs)
     if err != nil {
       logger.Errorf("sync status failed. If the message size is too large, "+
         "please increase the value of cluster.MaxCallSendMsgSize in configuration: %v", err)
     }
   }
....
```

### PR DESCRIPTION
**Pull request by killua525**

### CODE REVIEW

File: pkg/object/statussynccontroller/statussynccontroller.go [hunk 1]
```diff
@@ -235,8 +235,7 @@ func (ssc *StatusSyncController) syncStatusToCluster(statusUnits map[string]*sta
 	if ssc.lastSyncStatusUnits != nil {
 		kvs := make(map[string]*string)
 		for k := range ssc.lastSyncStatusUnits {
-			if su, exists := statusUnits[k]; !exists {
-				k = su.clusterKey(ssc.superSpec.Super().Cluster().Layout())
+			if _, exists := statusUnits[k]; !exists {
```
Comment (xxx7xxxx) [inline pkg/object/statussynccontroller/statussynccontroller.go:238]:
```go
		for k, su := range ssc.lastSyncStatusUnits {
			if _, exists := statusUnits[k]; !exists {
				key := su.clusterKey(ssc.superSpec.Super().Cluster().Layout())
				kvs[key] = nil
			}
		}
```

It seems this kind of change will fix the problem totally, how about testing and applying it?

**Review by xxx7xxxx — APPROVED** [review]

**Review by localvar — APPROVED** [review]
